services:
    hardhat:
        container_name: hardhat
        build: .
        ports:
            - '8545:8545'
        volumes:
            - ../dlc-attestor-stack/attestor/observer/contracts:/app/dlc-solidity/deploymentFiles
        environment:
            - BTC_FEE_RECIPIENT=03edf233daf20679848c38450c7feca2b32601d8150a68559de8ffefda7a03bd87
            - NETWORK_NAME=hardhat-arb
