services:
    hardhat:
        container_name: hardhat
        build: .
        ports:
            - '8545:8545'
        volumes:
            - ../dlc-attestor-stack/attestor/observer/contracts:/app/dlc-solidity/deploymentFiles
        environment:
            - BTC_FEE_RECIPIENT=3D8kYzXXsvibCqWUu7RkXZTLcx5DzmckZ2
            - NETWORK_NAME=hardhat-arb
