name: hardhat-test

on:
    pull_request:
        branches:
            - dev
            - master
        types:
            - opened
            - reopened
            - synchronize

jobs:
    test:
        runs-on: ubuntu-latest
        name: Hardhat unit test
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Environment
              uses: actions/setup-node@v3
            - name: Test
              uses: ambersun1234/hardhat-test-action@v1
              with:
                  network: localhost
