name: hardhat-test

on:
    pull_request:
        branches:
            - dev
            - master
        types:
            - opened
            - reopened
            - synchronize

env:
    KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
    KEY2: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'
    KEY3: '0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a'

jobs:
    test:
        runs-on: ubuntu-latest
        name: Hardhat unit tests
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
            - name: Install the dependencies
              run: npm install
            - name: Run the tests
              run: npm run coverage
