name: hardhat-test

on:
    pull_request:
        branches:
            - dev
            - master
        types:
            - opened
            - reopened
            - synchronize

jobs:
    test:
        runs-on: ubuntu-latest
        name: Hardhat unit tests
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
            - name: 'Install the dependencies'
              run: 'npm install'
            - name: 'Run the tests'
              run: 'npm run test'
